typedef struct {
  char *name;
  char *mime_type;
  char *extension;
} mime_type;

mime_type mime_types[1024];
int num_mime_types;

void add_mime_type(char name[], char type[], char ext[]) {
  mime_types[num_mime_types].name = name;
  mime_types[num_mime_types].mime_type = type;
  mime_types[num_mime_types].extension = ext;
  num_mime_types++;
}

const char * ext_to_mime_type(char ext[]) {
  for (size_t i = 0; i < num_mime_types; i++) {
    if (strcmp(ext, mime_types[i].extension) == 0) {
      return mime_types[i].mime_type;
    }
  }
  return "application/octet-stream";
}

void assemble_mime_types() {
  add_mime_type("3D Crossword Plugin", "application/vnd.hzn-3d-crossword", ".x3d");
  add_mime_type("3GP", "video/3gpp", ".3gp");
  add_mime_type("3GP2", "video/3gpp2", ".3g2");
  add_mime_type("3GPP MSEQ File", "application/vnd.mseq", ".mseq");
  add_mime_type("3M Post It Notes", "application/vnd.3m.post-it-notes", ".pwn");
  add_mime_type("3rd Generation Partnership Project - Pic Large", "application/vnd.3gpp.pic-bw-large", ".plb");
  add_mime_type("3rd Generation Partnership Project - Pic Small", "application/vnd.3gpp.pic-bw-small", ".psb");
  add_mime_type("3rd Generation Partnership Project - Pic Var", "application/vnd.3gpp.pic-bw-var", ".pvb");
  add_mime_type("3rd Generation Partnership Project - Transaction Capabilities Application Part", "application/vnd.3gpp2.tcap", ".tcap");
  add_mime_type("7-Zip", "application/x-7z-compressed", ".7z");
  add_mime_type("AbiWord", "application/x-abiword", ".abw");
  add_mime_type("Ace Archive", "application/x-ace-compressed", ".ace");
  add_mime_type("Active Content Compression", "application/vnd.americandynamics.acc", ".acc");
  add_mime_type("ACU Cobol", "application/vnd.acucobol", ".acu");
  add_mime_type("ACU Cobol", "application/vnd.acucorp", ".atc");
  add_mime_type("Adaptive differential pulse-code modulation", "audio/adpcm", ".adp");
  add_mime_type("Adobe (Macropedia) Authorware - Binary File", "application/x-authorware-bin", ".aab");
  add_mime_type("Adobe (Macropedia) Authorware - Map", "application/x-authorware-map", ".aam");
  add_mime_type("Adobe (Macropedia) Authorware - Segment File", "application/x-authorware-seg", ".aas");
  add_mime_type("Adobe AIR Application", "application/vnd.adobe.air-application-installer-package+zip", ".air");
  add_mime_type("Adobe Flash", "application/x-shockwave-flash", ".swf");
  add_mime_type("Adobe Flex Project", "application/vnd.adobe.fxp", ".fxp");
  add_mime_type("Adobe Portable Document Format", "application/pdf", ".pdf");
  add_mime_type("Adobe PostScript Printer Description File Format", "application/vnd.cups-ppd", ".ppd");
  add_mime_type("Adobe Shockwave Player", "application/x-director", ".dir");
  add_mime_type("Adobe XML Data Package", "application/vnd.adobe.xdp+xml", ".xdp");
  add_mime_type("Adobe XML Forms Data Format", "application/vnd.adobe.xfdf", ".xfdf");
  add_mime_type("Advanced Audio Coding (AAC)", "audio/x-aac", ".aac");
  add_mime_type("Ahead AIR Application", "application/vnd.ahead.space", ".ahead");
  add_mime_type("AirZip FileSECURE", "application/vnd.airzip.filesecure.azf", ".azf");
  add_mime_type("AirZip FileSECURE", "application/vnd.airzip.filesecure.azs", ".azs");
  add_mime_type("Amazon Kindle eBook format", "application/vnd.amazon.ebook", ".azw");
  add_mime_type("AmigaDE", "application/vnd.amiga.ami", ".ami");
  add_mime_type("Andrew Toolkit", "application/andrew-inset", "N/A");
  add_mime_type("Android Package Archive", "application/vnd.android.package-archive", ".apk");
  add_mime_type("ANSER-WEB Terminal Client - Certificate Issue", "application/vnd.anser-web-certificate-issue-initiation", ".cii");
  add_mime_type("ANSER-WEB Terminal Client - Web Funds Transfer", "application/vnd.anser-web-funds-transfer-initiation", ".fti");
  add_mime_type("Antix Game Player", "application/vnd.antix.game-component", ".atx");
  add_mime_type("Apple Installer Package", "application/vnd.apple.installer+xml", ".mpkg");
  add_mime_type("Applixware", "application/applixware", ".aw");
  add_mime_type("Archipelago Lesson Player", "application/vnd.hhe.lesson-player", ".les");
  add_mime_type("Arista Networks Software Image", "application/vnd.aristanetworks.swi", ".swi");
  add_mime_type("Assembler Source File", "text/x-asm", ".s");
  add_mime_type("Atom Publishing Protocol", "application/atomcat+xml", ".atomcat");
  add_mime_type("Atom Publishing Protocol Service Document", "application/atomsvc+xml", ".atomsvc");
  add_mime_type("Atom Syndication Format", "application/atom+xml", ".atom");
  add_mime_type("Attribute Certificate", "application/pkix-attr-cert", ".ac");
  add_mime_type("Audio Interchange File Format", "audio/x-aiff", ".aif");
  add_mime_type("Audio Video Interleave (AVI)", "video/x-msvideo", ".avi");
  add_mime_type("Audiograph", "application/vnd.audiograph", ".aep");
  add_mime_type("AutoCAD DXF", "image/vnd.dxf", ".dxf");
  add_mime_type("Autodesk Design Web Format (DWF)", "model/vnd.dwf", ".dwf");
  add_mime_type("BAS Partitur Format", "text/plain-bas", ".par");
  add_mime_type("Binary CPIO Archive", "application/x-bcpio", ".bcpio");
  add_mime_type("Binary Data", "application/octet-stream", ".bin");
  add_mime_type("Bitmap Image File", "image/bmp", ".bmp");
  add_mime_type("BitTorrent", "application/x-bittorrent", ".torrent");
  add_mime_type("Blackberry COD File", "application/vnd.rim.cod", ".cod");
  add_mime_type("Blueice Research Multipass", "application/vnd.blueice.multipass", ".mpm");
  add_mime_type("BMI Drawing Data Interchange", "application/vnd.bmi", ".bmi");
  add_mime_type("Bourne Shell Script", "application/x-sh", ".sh");
  add_mime_type("BTIF", "image/prs.btif", ".btif");
  add_mime_type("BusinessObjects", "application/vnd.businessobjects", ".rep");
  add_mime_type("Bzip Archive", "application/x-bzip", ".bz");
  add_mime_type("Bzip2 Archive", "application/x-bzip2", ".bz2");
  add_mime_type("C Shell Script", "application/x-csh", ".csh");
  add_mime_type("C Source File", "text/x-c", ".c");
  add_mime_type("CambridgeSoft Chem Draw", "application/vnd.chemdraw+xml", ".cdxml");
  add_mime_type("Cascading Style Sheets (CSS)", "text/css", ".css");
  add_mime_type("ChemDraw eXchange file", "chemical/x-cdx", ".cdx");
  add_mime_type("Chemical Markup Language", "chemical/x-cml", ".cml");
  add_mime_type("Chemical Style Markup Language", "chemical/x-csml", ".csml");
  add_mime_type("CIM Database", "application/vnd.contact.cmsg", ".cdbcmsg");
  add_mime_type("Claymore Data Files", "application/vnd.claymore", ".cla");
  add_mime_type("Clonk Game", "application/vnd.clonk.c4group", ".c4g");
  add_mime_type("Close Captioning - Subtitle", "image/vnd.dvb.subtitle", ".sub");
  add_mime_type("Cloud Data Management Interface (CDMI) - Capability", "application/cdmi-capability", ".cdmia");
  add_mime_type("Cloud Data Management Interface (CDMI) - Contaimer", "application/cdmi-container", ".cdmic");
  add_mime_type("Cloud Data Management Interface (CDMI) - Domain", "application/cdmi-domain", ".cdmid");
  add_mime_type("Cloud Data Management Interface (CDMI) - Object", "application/cdmi-object", ".cdmio");
  add_mime_type("Cloud Data Management Interface (CDMI) - Queue", "application/cdmi-queue", ".cdmiq");
  add_mime_type("ClueTrust CartoMobile - Config", "application/vnd.cluetrust.cartomobile-config", ".c11amc");
  add_mime_type("ClueTrust CartoMobile - Config Package", "application/vnd.cluetrust.cartomobile-config-pkg", ".c11amz");
  add_mime_type("CMU Image", "image/x-cmu-raster", ".ras");
  add_mime_type("COLLADA", "model/vnd.collada+xml", ".dae");
  add_mime_type("Comma-Seperated Values", "text/csv", ".csv");
  add_mime_type("Compact Pro", "application/mac-compactpro", ".cpt");
  add_mime_type("Compiled Wireless Markup Language (WMLC)", "application/vnd.wap.wmlc", ".wmlc");
  add_mime_type("Computer Graphics Metafile", "image/cgm", ".cgm");
  add_mime_type("CoolTalk", "x-conference/x-cooltalk", ".ice");
  add_mime_type("Corel Metafile Exchange (CMX)", "image/x-cmx", ".cmx");
  add_mime_type("CorelXARA", "application/vnd.xara", ".xar");
  add_mime_type("CosmoCaller", "application/vnd.cosmocaller", ".cmc");
  add_mime_type("CPIO Archive", "application/x-cpio", ".cpio");
  add_mime_type("CrickSoftware - Clicker", "application/vnd.crick.clicker", ".clkx");
  add_mime_type("CrickSoftware - Clicker - Keyboard", "application/vnd.crick.clicker.keyboard", ".clkk");
  add_mime_type("CrickSoftware - Clicker - Palette", "application/vnd.crick.clicker.palette", ".clkp");
  add_mime_type("CrickSoftware - Clicker - Template", "application/vnd.crick.clicker.template", ".clkt");
  add_mime_type("CrickSoftware - Clicker - Wordbank", "application/vnd.crick.clicker.wordbank", ".clkw");
  add_mime_type("Critical Tools - PERT Chart EXPERT", "application/vnd.criticaltools.wbs+xml", ".wbs");
  add_mime_type("CryptoNote", "application/vnd.rig.cryptonote", ".cryptonote");
  add_mime_type("Crystallographic Interchange Format", "chemical/x-cif", ".cif");
  add_mime_type("CrystalMaker Data Format", "chemical/x-cmdf", ".cmdf");
  add_mime_type("CU-SeeMe", "application/cu-seeme", ".cu");
  add_mime_type("CU-Writer", "application/prs.cww", ".cww");
  add_mime_type("Curl - Applet", "text/vnd.curl", ".curl");
  add_mime_type("Curl - Detached Applet", "text/vnd.curl.dcurl", ".dcurl");
  add_mime_type("Curl - Manifest File", "text/vnd.curl.mcurl", ".mcurl");
  add_mime_type("Curl - Source Code", "text/vnd.curl.scurl", ".scurl");
  add_mime_type("CURL Applet", "application/vnd.curl.car", ".car");
  add_mime_type("CURL Applet", "application/vnd.curl.pcurl", ".pcurl");
  add_mime_type("CustomMenu", "application/vnd.yellowriver-custom-menu", ".cmp");
  add_mime_type("Data Structure for the Security Suitability of Cryptographic Algorithms", "application/dssc+der", ".dssc");
  add_mime_type("Data Structure for the Security Suitability of Cryptographic Algorithms", "application/dssc+xml", ".xdssc");
  add_mime_type("Debian Package", "application/x-debian-package", ".deb");
  add_mime_type("DECE Audio", "audio/vnd.dece.audio", ".uva");
  add_mime_type("DECE Graphic", "image/vnd.dece.graphic", ".uvi");
  add_mime_type("DECE High Definition Video", "video/vnd.dece.hd", ".uvh");
  add_mime_type("DECE Mobile Video", "video/vnd.dece.mobile", ".uvm");
  add_mime_type("DECE MP4", "video/vnd.uvvu.mp4", ".uvu");
  add_mime_type("DECE PD Video", "video/vnd.dece.pd", ".uvp");
  add_mime_type("DECE SD Video", "video/vnd.dece.sd", ".uvs");
  add_mime_type("DECE Video", "video/vnd.dece.video", ".uvv");
  add_mime_type("Device Independent File Format (DVI)", "application/x-dvi", ".dvi");
  add_mime_type("Digital Siesmograph Networks - SEED Datafiles", "application/vnd.fdsn.seed", ".seed");
  add_mime_type("Digital Talking Book", "application/x-dtbook+xml", ".dtb");
  add_mime_type("Digital Talking Book - Resource File", "application/x-dtbresource+xml", ".res");
  add_mime_type("Digital Video Broadcasting", "application/vnd.dvb.ait", ".ait");
  add_mime_type("Digital Video Broadcasting", "application/vnd.dvb.service", ".svc");
  add_mime_type("Digital Winds Music", "audio/vnd.digital-winds", ".eol");
  add_mime_type("DjVu", "image/vnd.djvu", ".djvu");
  add_mime_type("Document Type Definition", "application/xml-dtd", ".dtd");
  add_mime_type("Dolby Meridian Lossless Packing", "application/vnd.dolby.mlp", ".mlp");
  add_mime_type("Doom Video Game", "application/x-doom", ".wad");
  add_mime_type("DPGraph", "application/vnd.dpgraph", ".dpg");
  add_mime_type("DRA Audio", "audio/vnd.dra", ".dra");
  add_mime_type("DreamFactory", "application/vnd.dreamfactory", ".dfac");
  add_mime_type("DTS Audio", "audio/vnd.dts", ".dts");
  add_mime_type("DTS High Definition Audio", "audio/vnd.dts.hd", ".dtshd");
  add_mime_type("DWG Drawing", "image/vnd.dwg", ".dwg");
  add_mime_type("DynaGeo", "application/vnd.dynageo", ".geo");
  add_mime_type("ECMAScript", "application/ecmascript", ".es");
  add_mime_type("EcoWin Chart", "application/vnd.ecowin.chart", ".mag");
  add_mime_type("EDMICS 2000", "image/vnd.fujixerox.edmics-mmr", ".mmr");
  add_mime_type("EDMICS 2000", "image/vnd.fujixerox.edmics-rlc", ".rlc");
  add_mime_type("Efficient XML Interchange", "application/exi", ".exi");
  add_mime_type("EFI Proteus", "application/vnd.proteus.magazine", ".mgz");
  add_mime_type("Electronic Publication", "application/epub+zip", ".epub");
  add_mime_type("Email Message", "message/rfc822", ".eml");
  add_mime_type("Enliven Viewer", "application/vnd.enliven", ".nml");
  add_mime_type("Express by Infoseek", "application/vnd.is-xpr", ".xpr");
  add_mime_type("eXtended Image File Format (XIFF)", "image/vnd.xiff", ".xif");
  add_mime_type("Extensible Forms Description Language", "application/vnd.xfdl", ".xfdl");
  add_mime_type("Extensible MultiModal Annotation", "application/emma+xml", ".emma");
  add_mime_type("EZPix Secure Photo Album", "application/vnd.ezpix-album", ".ez2");
  add_mime_type("EZPix Secure Photo Album", "application/vnd.ezpix-package", ".ez3");
  add_mime_type("FAST Search & Transfer ASA", "image/vnd.fst", ".fst");
  add_mime_type("FAST Search & Transfer ASA", "video/vnd.fvt", ".fvt");
  add_mime_type("FastBid Sheet", "image/vnd.fastbidsheet", ".fbs");
  add_mime_type("FCS Express Layout Link", "application/vnd.denovo.fcselayout-link", ".fe_launch");
  add_mime_type("Flash Video", "video/x-f4v", ".f4v");
  add_mime_type("Flash Video", "video/x-flv", ".flv");
  add_mime_type("FlashPix", "image/vnd.fpx", ".fpx");
  add_mime_type("FlashPix", "image/vnd.net-fpx", ".npx");
  add_mime_type("FLEXSTOR", "text/vnd.fmi.flexstor", ".flx");
  add_mime_type("FLI/FLC Animation Format", "video/x-fli", ".fli");
  add_mime_type("FluxTime Clip", "application/vnd.fluxtime.clip", ".ftc");
  add_mime_type("Forms Data Format", "application/vnd.fdf", ".fdf");
  add_mime_type("Fortran Source File", "text/x-fortran", ".f");
  add_mime_type("FrameMaker Interchange Format", "application/vnd.mif", ".mif");
  add_mime_type("FrameMaker Normal Format", "application/vnd.framemaker", ".fm");
  add_mime_type("FreeHand MX", "image/x-freehand", ".fh");
  add_mime_type("Friendly Software Corporation", "application/vnd.fsc.weblaunch", ".fsc");
  add_mime_type("Frogans Player", "application/vnd.frogans.fnc", ".fnc");
  add_mime_type("Frogans Player", "application/vnd.frogans.ltf", ".ltf");
  add_mime_type("Fujitsu - Xerox 2D CAD Data", "application/vnd.fujixerox.ddd", ".ddd");
  add_mime_type("Fujitsu - Xerox DocuWorks", "application/vnd.fujixerox.docuworks", ".xdw");
  add_mime_type("Fujitsu - Xerox DocuWorks Binder", "application/vnd.fujixerox.docuworks.binder", ".xbd");
  add_mime_type("Fujitsu Oasys", "application/vnd.fujitsu.oasys", ".oas");
  add_mime_type("Fujitsu Oasys", "application/vnd.fujitsu.oasys2", ".oa2");
  add_mime_type("Fujitsu Oasys", "application/vnd.fujitsu.oasys3", ".oa3");
  add_mime_type("Fujitsu Oasys", "application/vnd.fujitsu.oasysgp", ".fg5");
  add_mime_type("Fujitsu Oasys", "application/vnd.fujitsu.oasysprs", ".bh2");
  add_mime_type("FutureSplash Animator", "application/x-futuresplash", ".spl");
  add_mime_type("FuzzySheet", "application/vnd.fuzzysheet", ".fzs");
  add_mime_type("G3 Fax Image", "image/g3fax", ".g3");
  add_mime_type("GameMaker ActiveX", "application/vnd.gmx", ".gmx");
  add_mime_type("Gen-Trix Studio", "model/vnd.gtw", ".gtw");
  add_mime_type("Genomatix Tuxedo Framework", "application/vnd.genomatix.tuxedo", ".txd");
  add_mime_type("GeoGebra", "application/vnd.geogebra.file", ".ggb");
  add_mime_type("GeoGebra", "application/vnd.geogebra.tool", ".ggt");
  add_mime_type("Geometric Description Language (GDL)", "model/vnd.gdl", ".gdl");
  add_mime_type("GeoMetry Explorer", "application/vnd.geometry-explorer", ".gex");
  add_mime_type("GEONExT and JSXGraph", "application/vnd.geonext", ".gxt");
  add_mime_type("GeoplanW", "application/vnd.geoplan", ".g2w");
  add_mime_type("GeospacW", "application/vnd.geospace", ".g3w");
  add_mime_type("Ghostscript Font", "application/x-font-ghostscript", ".gsf");
  add_mime_type("Glyph Bitmap Distribution Format", "application/x-font-bdf", ".bdf");
  add_mime_type("GNU Tar Files", "application/x-gtar", ".gtar");
  add_mime_type("GNU Texinfo Document", "application/x-texinfo", ".texinfo");
  add_mime_type("Gnumeric", "application/x-gnumeric", ".gnumeric");
  add_mime_type("Google Earth - KML", "application/vnd.google-earth.kml+xml", ".kml");
  add_mime_type("Google Earth - Zipped KML", "application/vnd.google-earth.kmz", ".kmz");
  add_mime_type("GrafEq", "application/vnd.grafeq", ".gqf");
  add_mime_type("Graphics Interchange Format", "image/gif", ".gif");
  add_mime_type("Graphviz", "text/vnd.graphviz", ".gv");
  add_mime_type("Groove - Account", "application/vnd.groove-account", ".gac");
  add_mime_type("Groove - Help", "application/vnd.groove-help", ".ghf");
  add_mime_type("Groove - Identity Message", "application/vnd.groove-identity-message", ".gim");
  add_mime_type("Groove - Injector", "application/vnd.groove-injector", ".grv");
  add_mime_type("Groove - Tool Message", "application/vnd.groove-tool-message", ".gtm");
  add_mime_type("Groove - Tool Template", "application/vnd.groove-tool-template", ".tpl");
  add_mime_type("Groove - Vcard", "application/vnd.groove-vcard", ".vcg");
  add_mime_type("H.261", "video/h261", ".h261");
  add_mime_type("H.263", "video/h263", ".h263");
  add_mime_type("H.264", "video/h264", ".h264");
  add_mime_type("Hewlett Packard Instant Delivery", "application/vnd.hp-hpid", ".hpid");
  add_mime_type("Hewlett-Packard's WebPrintSmart", "application/vnd.hp-hps", ".hps");
  add_mime_type("Hierarchical Data Format", "application/x-hdf", ".hdf");
  add_mime_type("Hit\"n\"Mix", "audio/vnd.rip", ".rip");
  add_mime_type("Homebanking Computer Interface (HBCI)", "application/vnd.hbci", ".hbci");
  add_mime_type("HP Indigo Digital Press - Job Layout Languate", "application/vnd.hp-jlyt", ".jlt");
  add_mime_type("HP Printer Command Language", "application/vnd.hp-pcl", ".pcl");
  add_mime_type("HP-GL/2 and HP RTL", "application/vnd.hp-hpgl", ".hpgl");
  add_mime_type("HV Script", "application/vnd.yamaha.hv-script", ".hvs");
  add_mime_type("HV Voice Dictionary", "application/vnd.yamaha.hv-dic", ".hvd");
  add_mime_type("HV Voice Parameter", "application/vnd.yamaha.hv-voice", ".hvp");
  add_mime_type("Hydrostatix Master Suite", "application/vnd.hydrostatix.sof-data", ".sfd-hdstx");
  add_mime_type("Hyperstudio", "application/hyperstudio", ".stk");
  add_mime_type("Hypertext Application Language", "application/vnd.hal+xml", ".hal");
  add_mime_type("HyperText Markup Language (HTML)", "text/html", ".html");
  add_mime_type("IBM DB2 Rights Manager", "application/vnd.ibm.rights-management", ".irm");
  add_mime_type("IBM Electronic Media Management System - Secure Container", "application/vnd.ibm.secure-container", ".sc");
  add_mime_type("iCalendar", "text/calendar", ".ics");
  add_mime_type("ICC profile", "application/vnd.iccprofile", ".icc");
  add_mime_type("Icon Image", "image/x-icon", ".ico");
  add_mime_type("igLoader", "application/vnd.igloader", ".igl");
  add_mime_type("Image Exchange Format", "image/ief", ".ief");
  add_mime_type("ImmerVision PURE Players", "application/vnd.immervision-ivp", ".ivp");
  add_mime_type("ImmerVision PURE Players", "application/vnd.immervision-ivu", ".ivu");
  add_mime_type("IMS Networks", "application/reginfo+xml", ".rif");
  add_mime_type("In3D - 3DML", "text/vnd.in3d.3dml", ".3dml");
  add_mime_type("In3D - 3DML", "text/vnd.in3d.spot", ".spot");
  add_mime_type("Initial Graphics Exchange Specification (IGES)", "model/iges", ".igs");
  add_mime_type("Interactive Geometry Software", "application/vnd.intergeo", ".i2g");
  add_mime_type("Interactive Geometry Software Cinderella", "application/vnd.cinderella", ".cdy");
  add_mime_type("Intercon FormNet", "application/vnd.intercon.formnet", ".xpw");
  add_mime_type("International Society for Advancement of Cytometry", "application/vnd.isac.fcs", ".fcs");
  add_mime_type("Internet Protocol Flow Information Export", "application/ipfix", ".ipfix");
  add_mime_type("Internet Public Key Infrastructure - Certificate", "application/pkix-cert", ".cer");
  add_mime_type("Internet Public Key Infrastructure - Certificate Management Protocole", "application/pkixcmp", ".pki");
  add_mime_type("Internet Public Key Infrastructure - Certificate Revocation Lists", "application/pkix-crl", ".crl");
  add_mime_type("Internet Public Key Infrastructure - Certification Path", "application/pkix-pkipath", ".pkipath");
  add_mime_type("IOCOM Visimeet", "application/vnd.insors.igm", ".igm");
  add_mime_type("IP Unplugged Roaming Client", "application/vnd.ipunplugged.rcprofile", ".rcprofile");
  add_mime_type("iRepository / Lucidoc Editor", "application/vnd.irepository.package+xml", ".irp");
  add_mime_type("J2ME App Descriptor", "text/vnd.sun.j2me.app-descriptor", ".jad");
  add_mime_type("Java Archive", "application/java-archive", ".jar");
  add_mime_type("Java Bytecode File", "application/java-vm", ".class");
  add_mime_type("Java Network Launching Protocol", "application/x-java-jnlp-file", ".jnlp");
  add_mime_type("Java Serialized Object", "application/java-serialized-object", ".ser");
  add_mime_type("Java Source File", "text/x-java-source,java", ".java");
  add_mime_type("JavaScript", "application/javascript", ".js");
  add_mime_type("JavaScript Object Notation (JSON)", "application/json", ".json");
  add_mime_type("Joda Archive", "application/vnd.joost.joda-archive", ".joda");
  add_mime_type("JPEG 2000 Compound Image File Format", "video/jpm", ".jpm");
  add_mime_type("JPEG Image", "image/jpeg", ".jpeg");
  add_mime_type("JPEG Image", "image/jpeg", ".jpg");
  add_mime_type("JPEG Image (Progressive)", "image/pjpeg", ".pjpeg");
  add_mime_type("JPGVideo", "video/jpeg", ".jpgv");
  add_mime_type("Kahootz", "application/vnd.kahootz", ".ktz");
  add_mime_type("Karaoke on Chipnuts Chipsets", "application/vnd.chipnuts.karaoke-mmd", ".mmd");
  add_mime_type("KDE KOffice Office Suite - Karbon", "application/vnd.kde.karbon", ".karbon");
  add_mime_type("KDE KOffice Office Suite - KChart", "application/vnd.kde.kchart", ".chrt");
  add_mime_type("KDE KOffice Office Suite - Kformula", "application/vnd.kde.kformula", ".kfo");
  add_mime_type("KDE KOffice Office Suite - Kivio", "application/vnd.kde.kivio", ".flw");
  add_mime_type("KDE KOffice Office Suite - Kontour", "application/vnd.kde.kontour", ".kon");
  add_mime_type("KDE KOffice Office Suite - Kpresenter", "application/vnd.kde.kpresenter", ".kpr");
  add_mime_type("KDE KOffice Office Suite - Kspread", "application/vnd.kde.kspread", ".ksp");
  add_mime_type("KDE KOffice Office Suite - Kword", "application/vnd.kde.kword", ".kwd");
  add_mime_type("Kenamea App", "application/vnd.kenameaapp", ".htke");
  add_mime_type("Kidspiration", "application/vnd.kidspiration", ".kia");
  add_mime_type("Kinar Applications", "application/vnd.kinar", ".kne");
  add_mime_type("Kodak Storyshare", "application/vnd.kodak-descriptor", ".sse");
  add_mime_type("Laser App Enterprise", "application/vnd.las.las+xml", ".lasxml");
  add_mime_type("LaTeX", "application/x-latex", ".latex");
  add_mime_type("Life Balance - Desktop Edition", "application/vnd.llamagraphics.life-balance.desktop", ".lbd");
  add_mime_type("Life Balance - Exchange Format", "application/vnd.llamagraphics.life-balance.exchange+xml", ".lbe");
  add_mime_type("Lightspeed Audio Lab", "application/vnd.jam", ".jam");
  add_mime_type("Lotus 1-2-3", "application/vnd.lotus-1-2-3", "0.123");
  add_mime_type("Lotus Approach", "application/vnd.lotus-approach", ".apr");
  add_mime_type("Lotus Freelance", "application/vnd.lotus-freelance", ".pre");
  add_mime_type("Lotus Notes", "application/vnd.lotus-notes", ".nsf");
  add_mime_type("Lotus Organizer", "application/vnd.lotus-organizer", ".org");
  add_mime_type("Lotus Screencam", "application/vnd.lotus-screencam", ".scm");
  add_mime_type("Lotus Wordpro", "application/vnd.lotus-wordpro", ".lwp");
  add_mime_type("Lucent Voice", "audio/vnd.lucent.voice", ".lvp");
  add_mime_type("M3U (Multimedia Playlist)", "audio/x-mpegurl", ".m3u");
  add_mime_type("M4v", "video/x-m4v", ".m4v");
  add_mime_type("Macintosh BinHex 4.0", "application/mac-binhex40", ".hqx");
  add_mime_type("MacPorts Port System", "application/vnd.macports.portpkg", ".portpkg");
  add_mime_type("MapGuide DBXML", "application/vnd.osgeo.mapguide.package", ".mgp");
  add_mime_type("MARC Formats", "application/marc", ".mrc");
  add_mime_type("MARC21 XML Schema", "application/marcxml+xml", ".mrcx");
  add_mime_type("Material Exchange Format", "application/mxf", ".mxf");
  add_mime_type("Mathematica Notebook Player", "application/vnd.wolfram.player", ".nbp");
  add_mime_type("Mathematica Notebooks", "application/mathematica", ".ma");
  add_mime_type("Mathematical Markup Language", "application/mathml+xml", ".mathml");
  add_mime_type("Mbox database files", "application/mbox", ".mbox");
  add_mime_type("MedCalc", "application/vnd.medcalcdata", ".mc1");
  add_mime_type("Media Server Control Markup Language", "application/mediaservercontrol+xml", ".mscml");
  add_mime_type("MediaRemote", "application/vnd.mediastation.cdkey", ".cdkey");
  add_mime_type("Medical Waveform Encoding Format", "application/vnd.mfer", ".mwf");
  add_mime_type("Melody Format for Mobile Platform", "application/vnd.mfmp", ".mfm");
  add_mime_type("Mesh Data Type", "model/mesh", ".msh");
  add_mime_type("Metadata Authority Description Schema", "application/mads+xml", ".mads");
  add_mime_type("Metadata Encoding and Transmission Standard", "application/mets+xml", ".mets");
  add_mime_type("Metadata Object Description Schema", "application/mods+xml", ".mods");
  add_mime_type("Metalink", "application/metalink4+xml", ".meta4");
  add_mime_type("Micro CADAM Helix D&D", "application/vnd.mcd", ".mcd");
  add_mime_type("Micrografx", "application/vnd.micrografx.flo", ".flo");
  add_mime_type("Micrografx iGrafx Professional", "application/vnd.micrografx.igx", ".igx");
  add_mime_type("MICROSEC e-Szign¢", "application/vnd.eszigno3+xml", ".es3");
  add_mime_type("Microsoft Access", "application/x-msaccess", ".mdb");
  add_mime_type("Microsoft Advanced Systems Format (ASF)", "video/x-ms-asf", ".asf");
  add_mime_type("Microsoft Application", "application/x-msdownload", ".exe");
  add_mime_type("Microsoft Artgalry", "application/vnd.ms-artgalry", ".cil");
  add_mime_type("Microsoft Cabinet File", "application/vnd.ms-cab-compressed", ".cab");
  add_mime_type("Microsoft Class Server", "application/vnd.ms-ims", ".ims");
  add_mime_type("Microsoft ClickOnce", "application/x-ms-application", ".application");
  add_mime_type("Microsoft Clipboard Clip", "application/x-msclip", ".clp");
  add_mime_type("Microsoft Document Imaging Format", "image/vnd.ms-modi", ".mdi");
  add_mime_type("Microsoft Embedded OpenType", "application/vnd.ms-fontobject", ".eot");
  add_mime_type("Microsoft Excel", "application/vnd.ms-excel", ".xls");
  add_mime_type("Microsoft Excel - Add-In File", "application/vnd.ms-excel.addin.macroenabled.12", ".xlam");
  add_mime_type("Microsoft Excel - Binary Workbook", "application/vnd.ms-excel.sheet.binary.macroenabled.12", ".xlsb");
  add_mime_type("Microsoft Excel - Macro-Enabled Template File", "application/vnd.ms-excel.template.macroenabled.12", ".xltm");
  add_mime_type("Microsoft Excel - Macro-Enabled Workbook", "application/vnd.ms-excel.sheet.macroenabled.12", ".xlsm");
  add_mime_type("Microsoft Html Help File", "application/vnd.ms-htmlhelp", ".chm");
  add_mime_type("Microsoft Information Card", "application/x-mscardfile", ".crd");
  add_mime_type("Microsoft Learning Resource Module", "application/vnd.ms-lrm", ".lrm");
  add_mime_type("Microsoft MediaView", "application/x-msmediaview", ".mvb");
  add_mime_type("Microsoft Money", "application/x-msmoney", ".mny");
  add_mime_type("Microsoft Office - OOXML - Presentation", "application/vnd.openxmlformats-officedocument.presentationml.presentation", ".pptx");
  add_mime_type("Microsoft Office - OOXML - Presentation (Slide)", "application/vnd.openxmlformats-officedocument.presentationml.slide", ".sldx");
  add_mime_type("Microsoft Office - OOXML - Presentation (Slideshow)", "application/vnd.openxmlformats-officedocument.presentationml.slideshow", ".ppsx");
  add_mime_type("Microsoft Office - OOXML - Presentation Template", "application/vnd.openxmlformats-officedocument.presentationml.template", ".potx");
  add_mime_type("Microsoft Office - OOXML - Spreadsheet", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", ".xlsx");
  add_mime_type("Microsoft Office - OOXML - Spreadsheet Template", "application/vnd.openxmlformats-officedocument.spreadsheetml.template", ".xltx");
  add_mime_type("Microsoft Office - OOXML - Word Document", "application/vnd.openxmlformats-officedocument.wordprocessingml.document", ".docx");
  add_mime_type("Microsoft Office - OOXML - Word Document Template", "application/vnd.openxmlformats-officedocument.wordprocessingml.template", ".dotx");
  add_mime_type("Microsoft Office Binder", "application/x-msbinder", ".obd");
  add_mime_type("Microsoft Office System Release Theme", "application/vnd.ms-officetheme", ".thmx");
  add_mime_type("Microsoft OneNote", "application/onenote", ".onetoc");
  add_mime_type("Microsoft PlayReady Ecosystem", "audio/vnd.ms-playready.media.pya", ".pya");
  add_mime_type("Microsoft PlayReady Ecosystem Video", "video/vnd.ms-playready.media.pyv", ".pyv");
  add_mime_type("Microsoft PowerPoint", "application/vnd.ms-powerpoint", ".ppt");
  add_mime_type("Microsoft PowerPoint - Add-in file", "application/vnd.ms-powerpoint.addin.macroenabled.12", ".ppam");
  add_mime_type("Microsoft PowerPoint - Macro-Enabled Open XML Slide", "application/vnd.ms-powerpoint.slide.macroenabled.12", ".sldm");
  add_mime_type("Microsoft PowerPoint - Macro-Enabled Presentation File", "application/vnd.ms-powerpoint.presentation.macroenabled.12", ".pptm");
  add_mime_type("Microsoft PowerPoint - Macro-Enabled Slide Show File", "application/vnd.ms-powerpoint.slideshow.macroenabled.12", ".ppsm");
  add_mime_type("Microsoft PowerPoint - Macro-Enabled Template File", "application/vnd.ms-powerpoint.template.macroenabled.12", ".potm");
  add_mime_type("Microsoft Project", "application/vnd.ms-project", ".mpp");
  add_mime_type("Microsoft Publisher", "application/x-mspublisher", ".pub");
  add_mime_type("Microsoft Schedule+", "application/x-msschedule", ".scd");
  add_mime_type("Microsoft Silverlight", "application/x-silverlight-app", ".xap");
  add_mime_type("Microsoft Trust UI Provider - Certificate Trust Link", "application/vnd.ms-pki.stl", ".stl");
  add_mime_type("Microsoft Trust UI Provider - Security Catalog", "application/vnd.ms-pki.seccat", ".cat");
  add_mime_type("Microsoft Visio", "application/vnd.visio", ".vsd");
  add_mime_type("Microsoft Visio 2013", "application/vnd.visio2013", ".vsdx");
  add_mime_type("Microsoft Windows Media", "video/x-ms-wm", ".wm");
  add_mime_type("Microsoft Windows Media Audio", "audio/x-ms-wma", ".wma");
  add_mime_type("Microsoft Windows Media Audio Redirector", "audio/x-ms-wax", ".wax");
  add_mime_type("Microsoft Windows Media Audio/Video Playlist", "video/x-ms-wmx", ".wmx");
  add_mime_type("Microsoft Windows Media Player Download Package", "application/x-ms-wmd", ".wmd");
  add_mime_type("Microsoft Windows Media Player Playlist", "application/vnd.ms-wpl", ".wpl");
  add_mime_type("Microsoft Windows Media Player Skin Package", "application/x-ms-wmz", ".wmz");
  add_mime_type("Microsoft Windows Media Video", "video/x-ms-wmv", ".wmv");
  add_mime_type("Microsoft Windows Media Video Playlist", "video/x-ms-wvx", ".wvx");
  add_mime_type("Microsoft Windows Metafile", "application/x-msmetafile", ".wmf");
  add_mime_type("Microsoft Windows Terminal Services", "application/x-msterminal", ".trm");
  add_mime_type("Microsoft Word", "application/msword", ".doc");
  add_mime_type("Microsoft Word - Macro-Enabled Document", "application/vnd.ms-word.document.macroenabled.12", ".docm");
  add_mime_type("Microsoft Word - Macro-Enabled Template", "application/vnd.ms-word.template.macroenabled.12", ".dotm");
  add_mime_type("Microsoft Wordpad", "application/x-mswrite", ".wri");
  add_mime_type("Microsoft Works", "application/vnd.ms-works", ".wps");
  add_mime_type("Microsoft XAML Browser Application", "application/x-ms-xbap", ".xbap");
  add_mime_type("Microsoft XML Paper Specification", "application/vnd.ms-xpsdocument", ".xps");
  add_mime_type("MIDI - Musical Instrument Digital Interface", "audio/midi", ".mid");
  add_mime_type("MiniPay", "application/vnd.ibm.minipay", ".mpy");
  add_mime_type("MO:DCA-P", "application/vnd.ibm.modcap", ".afp");
  add_mime_type("Mobile Information Device Profile", "application/vnd.jcp.javame.midlet-rms", ".rms");
  add_mime_type("MobileTV", "application/vnd.tmobile-livetv", ".tmo");
  add_mime_type("Mobipocket", "application/x-mobipocket-ebook", ".prc");
  add_mime_type("Mobius Management Systems - Basket file", "application/vnd.mobius.mbk", ".mbk");
  add_mime_type("Mobius Management Systems - Distribution Database", "application/vnd.mobius.dis", ".dis");
  add_mime_type("Mobius Management Systems - Policy Definition Language File", "application/vnd.mobius.plc", ".plc");
  add_mime_type("Mobius Management Systems - Query File", "application/vnd.mobius.mqy", ".mqy");
  add_mime_type("Mobius Management Systems - Script Language", "application/vnd.mobius.msl", ".msl");
  add_mime_type("Mobius Management Systems - Topic Index File", "application/vnd.mobius.txf", ".txf");
  add_mime_type("Mobius Management Systems - UniversalArchive", "application/vnd.mobius.daf", ".daf");
  add_mime_type("mod_fly / fly.cgi", "text/vnd.fly", ".fly");
  add_mime_type("Mophun Certificate", "application/vnd.mophun.certificate", ".mpc");
  add_mime_type("Mophun VM", "application/vnd.mophun.application", ".mpn");
  add_mime_type("Motion JPEG 2000", "video/mj2", ".mj2");
  add_mime_type("MPEG Audio", "audio/mpeg", ".mpga");
  add_mime_type("MPEG Audio", "audio/mpeg", ".mp3");  
  add_mime_type("MPEG Url", "video/vnd.mpegurl", ".mxu");
  add_mime_type("MPEG Video", "video/mpeg", ".mpeg");
  add_mime_type("MPEG-21", "application/mp21", ".m21");
  add_mime_type("MPEG-4 Audio", "audio/mp4", ".mp4a");
  add_mime_type("MPEG-4 Video", "video/mp4", ".mp4");
  add_mime_type("MPEG4", "application/mp4", ".mp4");
  add_mime_type("Multimedia Playlist Unicode", "application/vnd.apple.mpegurl", ".m3u8");
  add_mime_type("MUsical Score Interpreted Code Invented for the ASCII designation of Notation", "application/vnd.musician", ".mus");
  add_mime_type("Muvee Automatic Video Editing", "application/vnd.muvee.style", ".msty");
  add_mime_type("MXML", "application/xv+xml", ".mxml");
  add_mime_type("N-Gage Game Data", "application/vnd.nokia.n-gage.data", ".ngdat");
  add_mime_type("N-Gage Game Installer", "application/vnd.nokia.n-gage.symbian.install", ".n-gage");
  add_mime_type("Navigation Control file for XML (for ePub)", "application/x-dtbncx+xml", ".ncx");
  add_mime_type("Network Common Data Form (NetCDF)", "application/x-netcdf", ".nc");
  add_mime_type("neuroLanguage", "application/vnd.neurolanguage.nlu", ".nlu");
  add_mime_type("New Moon Liftoff/DNA", "application/vnd.dna", ".dna");
  add_mime_type("NobleNet Directory", "application/vnd.noblenet-directory", ".nnd");
  add_mime_type("NobleNet Sealer", "application/vnd.noblenet-sealer", ".nns");
  add_mime_type("NobleNet Web", "application/vnd.noblenet-web", ".nnw");
  add_mime_type("Nokia Radio Application - Preset", "application/vnd.nokia.radio-preset", ".rpst");
  add_mime_type("Nokia Radio Application - Preset", "application/vnd.nokia.radio-presets", ".rpss");
  add_mime_type("Notation3", "text/n3", ".n3");
  add_mime_type("Novadigm's RADIA and EDM products", "application/vnd.novadigm.edm", ".edm");
  add_mime_type("Novadigm's RADIA and EDM products", "application/vnd.novadigm.edx", ".edx");
  add_mime_type("Novadigm's RADIA and EDM products", "application/vnd.novadigm.ext", ".ext");
  add_mime_type("NpGraphIt", "application/vnd.flographit", ".gph");
  add_mime_type("Nuera ECELP 4800", "audio/vnd.nuera.ecelp4800", ".ecelp4800");
  add_mime_type("Nuera ECELP 7470", "audio/vnd.nuera.ecelp7470", ".ecelp7470");
  add_mime_type("Nuera ECELP 9600", "audio/vnd.nuera.ecelp9600", ".ecelp9600");
  add_mime_type("Office Document Architecture", "application/oda", ".oda");
  add_mime_type("Ogg", "application/ogg", ".ogx");
  add_mime_type("Ogg Audio", "audio/ogg", ".oga");
  add_mime_type("Ogg Video", "video/ogg", ".ogv");
  add_mime_type("OMA Download Agents", "application/vnd.oma.dd2+xml", ".dd2");
  add_mime_type("Open Document Text Web", "application/vnd.oasis.opendocument.text-web", ".oth");
  add_mime_type("Open eBook Publication Structure", "application/oebps-package+xml", ".opf");
  add_mime_type("Open Financial Exchange", "application/vnd.intu.qbo", ".qbo");
  add_mime_type("Open Office Extension", "application/vnd.openofficeorg.extension", ".oxt");
  add_mime_type("Open Score Format", "application/vnd.yamaha.openscoreformat", ".osf");
  add_mime_type("Open Web Media Project - Audio", "audio/webm", ".weba");
  add_mime_type("Open Web Media Project - Video", "video/webm", ".webm");
  add_mime_type("OpenDocument Chart", "application/vnd.oasis.opendocument.chart", ".odc");
  add_mime_type("OpenDocument Chart Template", "application/vnd.oasis.opendocument.chart-template", ".otc");
  add_mime_type("OpenDocument Database", "application/vnd.oasis.opendocument.database", ".odb");
  add_mime_type("OpenDocument Formula", "application/vnd.oasis.opendocument.formula", ".odf");
  add_mime_type("OpenDocument Formula Template", "application/vnd.oasis.opendocument.formula-template", ".odft");
  add_mime_type("OpenDocument Graphics", "application/vnd.oasis.opendocument.graphics", ".odg");
  add_mime_type("OpenDocument Graphics Template", "application/vnd.oasis.opendocument.graphics-template", ".otg");
  add_mime_type("OpenDocument Image", "application/vnd.oasis.opendocument.image", ".odi");
  add_mime_type("OpenDocument Image Template", "application/vnd.oasis.opendocument.image-template", ".oti");
  add_mime_type("OpenDocument Presentation", "application/vnd.oasis.opendocument.presentation", ".odp");
  add_mime_type("OpenDocument Presentation Template", "application/vnd.oasis.opendocument.presentation-template", ".otp");
  add_mime_type("OpenDocument Spreadsheet", "application/vnd.oasis.opendocument.spreadsheet", ".ods");
  add_mime_type("OpenDocument Spreadsheet Template", "application/vnd.oasis.opendocument.spreadsheet-template", ".ots");
  add_mime_type("OpenDocument Text", "application/vnd.oasis.opendocument.text", ".odt");
  add_mime_type("OpenDocument Text Master", "application/vnd.oasis.opendocument.text-master", ".odm");
  add_mime_type("OpenDocument Text Template", "application/vnd.oasis.opendocument.text-template", ".ott");
  add_mime_type("OpenGL Textures (KTX)", "image/ktx", ".ktx");
  add_mime_type("OpenOffice - Calc (Spreadsheet)", "application/vnd.sun.xml.calc", ".sxc");
  add_mime_type("OpenOffice - Calc Template (Spreadsheet)", "application/vnd.sun.xml.calc.template", ".stc");
  add_mime_type("OpenOffice - Draw (Graphics)", "application/vnd.sun.xml.draw", ".sxd");
  add_mime_type("OpenOffice - Draw Template (Graphics)", "application/vnd.sun.xml.draw.template", ".std");
  add_mime_type("OpenOffice - Impress (Presentation)", "application/vnd.sun.xml.impress", ".sxi");
  add_mime_type("OpenOffice - Impress Template (Presentation)", "application/vnd.sun.xml.impress.template", ".sti");
  add_mime_type("OpenOffice - Math (Formula)", "application/vnd.sun.xml.math", ".sxm");
  add_mime_type("OpenOffice - Writer (Text - HTML)", "application/vnd.sun.xml.writer", ".sxw");
  add_mime_type("OpenOffice - Writer (Text - HTML)", "application/vnd.sun.xml.writer.global", ".sxg");
  add_mime_type("OpenOffice - Writer Template (Text - HTML)", "application/vnd.sun.xml.writer.template", ".stw");
  add_mime_type("OpenType Font File", "application/x-font-otf", ".otf");
  add_mime_type("OSFPVG", "application/vnd.yamaha.openscoreformat.osfpvg+xml", ".osfpvg");
  add_mime_type("OSGi Deployment Package", "application/vnd.osgi.dp", ".dp");
  add_mime_type("PalmOS Data", "application/vnd.palm", ".pdb");
  add_mime_type("Pascal Source File", "text/x-pascal", ".p");
  add_mime_type("PawaaFILE", "application/vnd.pawaafile", ".paw");
  add_mime_type("PCL 6 Enhanced (Formely PCL XL)", "application/vnd.hp-pclxl", ".pclxl");
  add_mime_type("Pcsel eFIF File", "application/vnd.picsel", ".efif");
  add_mime_type("PCX Image", "image/x-pcx", ".pcx");
  add_mime_type("Photoshop Document", "image/vnd.adobe.photoshop", ".psd");
  add_mime_type("PICSRules", "application/pics-rules", ".prf");
  add_mime_type("PICT Image", "image/x-pict", ".pic");
  add_mime_type("pIRCh", "application/x-chat", ".chat");
  add_mime_type("PKCS #10 - Certification Request Standard", "application/pkcs10", ".p10");
  add_mime_type("PKCS #12 - Personal Information Exchange Syntax Standard", "application/x-pkcs12", ".p12");
  add_mime_type("PKCS #7 - Cryptographic Message Syntax Standard", "application/pkcs7-mime", ".p7m");
  add_mime_type("PKCS #7 - Cryptographic Message Syntax Standard", "application/pkcs7-signature", ".p7s");
  add_mime_type("PKCS #7 - Cryptographic Message Syntax Standard (Certificate Request Response)", "application/x-pkcs7-certreqresp", ".p7r");
  add_mime_type("PKCS #7 - Cryptographic Message Syntax Standard (Certificates)", "application/x-pkcs7-certificates", ".p7b");
  add_mime_type("PKCS #8 - Private-Key Information Syntax Standard", "application/pkcs8", ".p8");
  add_mime_type("PocketLearn Viewers", "application/vnd.pocketlearn", ".plf");
  add_mime_type("Portable Anymap Image", "image/x-portable-anymap", ".pnm");
  add_mime_type("Portable Bitmap Format", "image/x-portable-bitmap", ".pbm");
  add_mime_type("Portable Compiled Format", "application/x-font-pcf", ".pcf");
  add_mime_type("Portable Font Resource", "application/font-tdpfr", ".pfr");
  add_mime_type("Portable Game Notation (Chess Games)", "application/x-chess-pgn", ".pgn");
  add_mime_type("Portable Graymap Format", "image/x-portable-graymap", ".pgm");
  add_mime_type("Portable Network Graphics (PNG)", "image/png", ".png");
  add_mime_type("Portable Network Graphics (PNG) (Citrix client)", "image/x-citrix-png", ".png");
  add_mime_type("Portable Network Graphics (PNG) (x-token)", "image/x-png", ".png");
  add_mime_type("Portable Pixmap Format", "image/x-portable-pixmap", ".ppm");
  add_mime_type("Portable Symmetric Key Container", "application/pskc+xml", ".pskcxml");
  add_mime_type("PosML", "application/vnd.ctc-posml", ".pml");
  add_mime_type("PostScript", "application/postscript", ".ai");
  add_mime_type("PostScript Fonts", "application/x-font-type1", ".pfa");
  add_mime_type("PowerBuilder", "application/vnd.powerbuilder6", ".pbd");
  add_mime_type("Pretty Good Privacy", "application/pgp-encrypted", ".pgp");
  add_mime_type("Pretty Good Privacy - Signature", "application/pgp-signature", ".pgp");
  add_mime_type("Preview Systems ZipLock/VBox", "application/vnd.previewsystems.box", ".box");
  add_mime_type("Princeton Video Image", "application/vnd.pvi.ptid1", ".ptid");
  add_mime_type("Pronunciation Lexicon Specification", "application/pls+xml", ".pls");
  add_mime_type("Proprietary P&G Standard Reporting System", "application/vnd.pg.format", ".str");
  add_mime_type("Proprietary P&G Standard Reporting System", "application/vnd.pg.osasli", ".ei6");
  add_mime_type("PRS Lines Tag", "text/prs.lines.tag", ".dsc");
  add_mime_type("PSF Fonts", "application/x-font-linux-psf", ".psf");
  add_mime_type("PubliShare Objects", "application/vnd.publishare-delta-tree", ".qps");
  add_mime_type("Qualcomm's Plaza Mobile Internet", "application/vnd.pmi.widget", ".wg");
  add_mime_type("QuarkXpress", "application/vnd.quark.quarkxpress", ".qxd");
  add_mime_type("QUASS Stream Player", "application/vnd.epson.esf", ".esf");
  add_mime_type("QUASS Stream Player", "application/vnd.epson.msf", ".msf");
  add_mime_type("QUASS Stream Player", "application/vnd.epson.ssf", ".ssf");
  add_mime_type("QuickAnime Player", "application/vnd.epson.quickanime", ".qam");
  add_mime_type("Quicken", "application/vnd.intu.qfx", ".qfx");
  add_mime_type("Quicktime Video", "video/quicktime", ".qt");
  add_mime_type("RAR Archive", "application/x-rar-compressed", ".rar");
  add_mime_type("Real Audio Sound", "audio/x-pn-realaudio", ".ram");
  add_mime_type("Real Audio Sound", "audio/x-pn-realaudio-plugin", ".rmp");
  add_mime_type("Really Simple Discovery", "application/rsd+xml", ".rsd");
  add_mime_type("RealMedia", "application/vnd.rn-realmedia", ".rm");
  add_mime_type("RealVNC", "application/vnd.realvnc.bed", ".bed");
  add_mime_type("Recordare Applications", "application/vnd.recordare.musicxml", ".mxl");
  add_mime_type("Recordare Applications", "application/vnd.recordare.musicxml+xml", ".musicxml");
  add_mime_type("Relax NG Compact Syntax", "application/relax-ng-compact-syntax", ".rnc");
  add_mime_type("RemoteDocs R-Viewer", "application/vnd.data-vision.rdz", ".rdz");
  add_mime_type("Resource Description Framework", "application/rdf+xml", ".rdf");
  add_mime_type("RetroPlatform Player", "application/vnd.cloanto.rp9", ".rp9");
  add_mime_type("RhymBox", "application/vnd.jisp", ".jisp");
  add_mime_type("Rich Text Format", "application/rtf", ".rtf");
  add_mime_type("Rich Text Format (RTF)", "text/richtext", ".rtx");
  add_mime_type("ROUTE 66 Location Based Services", "application/vnd.route66.link66+xml", ".link66");
  add_mime_type("RSS - Really Simple Syndication", "application/rss+xml", ".rss");
  add_mime_type("S Hexdump Format", "application/shf+xml", ".shf");
  add_mime_type("SailingTracker", "application/vnd.sailingtracker.track", ".st");
  add_mime_type("Scalable Vector Graphics (SVG)", "image/svg+xml", ".svg");
  add_mime_type("ScheduleUs", "application/vnd.sus-calendar", ".sus");
  add_mime_type("Search/Retrieve via URL Response Format", "application/sru+xml", ".sru");
  add_mime_type("Secure Electronic Transaction - Payment", "application/set-payment-initiation", ".setpay");
  add_mime_type("Secure Electronic Transaction - Registration", "application/set-registration-initiation", ".setreg");
  add_mime_type("Secured eMail", "application/vnd.sema", ".sema");
  add_mime_type("Secured eMail", "application/vnd.semd", ".semd");
  add_mime_type("Secured eMail", "application/vnd.semf", ".semf");
  add_mime_type("SeeMail", "application/vnd.seemail", ".see");
  add_mime_type("Server Normal Format", "application/x-font-snf", ".snf");
  add_mime_type("Server-Based Certificate Validation Protocol - Validation Policies - Request", "application/scvp-vp-request", ".spq");
  add_mime_type("Server-Based Certificate Validation Protocol - Validation Policies - Response", "application/scvp-vp-response", ".spp");
  add_mime_type("Server-Based Certificate Validation Protocol - Validation Request", "application/scvp-cv-request", ".scq");
  add_mime_type("Server-Based Certificate Validation Protocol - Validation Response", "application/scvp-cv-response", ".scs");
  add_mime_type("Session Description Protocol", "application/sdp", ".sdp");
  add_mime_type("Setext", "text/x-setext", ".etx");
  add_mime_type("SGI Movie", "video/x-sgi-movie", ".movie");
  add_mime_type("Shana Informed Filler", "application/vnd.shana.informed.formdata", ".ifm");
  add_mime_type("Shana Informed Filler", "application/vnd.shana.informed.formtemplate", ".itp");
  add_mime_type("Shana Informed Filler", "application/vnd.shana.informed.interchange", ".iif");
  add_mime_type("Shana Informed Filler", "application/vnd.shana.informed.package", ".ipk");
  add_mime_type("Sharing Transaction Fraud Data", "application/thraud+xml", ".tfi");
  add_mime_type("Shell Archive", "application/x-shar", ".shar");
  add_mime_type("Silicon Graphics RGB Bitmap", "image/x-rgb", ".rgb");
  add_mime_type("SimpleAnimeLite Player", "application/vnd.epson.salt", ".slt");
  add_mime_type("Simply Accounting", "application/vnd.accpac.simply.aso", ".aso");
  add_mime_type("Simply Accounting - Data Import", "application/vnd.accpac.simply.imp", ".imp");
  add_mime_type("SimTech MindMapper", "application/vnd.simtech-mindmapper", ".twd");
  add_mime_type("Sixth Floor Media - CommonSpace", "application/vnd.commonspace", ".csp");
  add_mime_type("SMAF Audio", "application/vnd.yamaha.smaf-audio", ".saf");
  add_mime_type("SMAF File", "application/vnd.smaf", ".mmf");
  add_mime_type("SMAF Phrase", "application/vnd.yamaha.smaf-phrase", ".spf");
  add_mime_type("SMART Technologies Apps", "application/vnd.smart.teacher", ".teacher");
  add_mime_type("SourceView Document", "application/vnd.svd", ".svd");
  add_mime_type("SPARQL - Query", "application/sparql-query", ".rq");
  add_mime_type("SPARQL - Results", "application/sparql-results+xml", ".srx");
  add_mime_type("Speech Recognition Grammar Specification", "application/srgs", ".gram");
  add_mime_type("Speech Recognition Grammar Specification - XML", "application/srgs+xml", ".grxml");
  add_mime_type("Speech Synthesis Markup Language", "application/ssml+xml", ".ssml");
  add_mime_type("SSEYO Koan Play File", "application/vnd.koan", ".skp");
  add_mime_type("Standard Generalized Markup Language (SGML)", "text/sgml", ".sgml");
  add_mime_type("StarOffice - Calc", "application/vnd.stardivision.calc", ".sdc");
  add_mime_type("StarOffice - Draw", "application/vnd.stardivision.draw", ".sda");
  add_mime_type("StarOffice - Impress", "application/vnd.stardivision.impress", ".sdd");
  add_mime_type("StarOffice - Math", "application/vnd.stardivision.math", ".smf");
  add_mime_type("StarOffice - Writer", "application/vnd.stardivision.writer", ".sdw");
  add_mime_type("StarOffice - Writer (Global)", "application/vnd.stardivision.writer-global", ".sgl");
  add_mime_type("StepMania", "application/vnd.stepmania.stepchart", ".sm");
  add_mime_type("Stuffit Archive", "application/x-stuffit", ".sit");
  add_mime_type("Stuffit Archive", "application/x-stuffitx", ".sitx");
  add_mime_type("SudokuMagic", "application/vnd.solent.sdkm+xml", ".sdkm");
  add_mime_type("Sugar Linux Application Bundle", "application/vnd.olpc-sugar", ".xo");
  add_mime_type("Sun Audio - Au file format", "audio/basic", ".au");
  add_mime_type("SundaHus WQ", "application/vnd.wqd", ".wqd");
  add_mime_type("Symbian Install Package", "application/vnd.symbian.install", ".sis");
  add_mime_type("Synchronized Multimedia Integration Language", "application/smil+xml", ".smi");
  add_mime_type("SyncML", "application/vnd.syncml+xml", ".xsm");
  add_mime_type("SyncML - Device Management", "application/vnd.syncml.dm+wbxml", ".bdm");
  add_mime_type("SyncML - Device Management", "application/vnd.syncml.dm+xml", ".xdm");
  add_mime_type("System V Release 4 CPIO Archive", "application/x-sv4cpio", ".sv4cpio");
  add_mime_type("System V Release 4 CPIO Checksum Data", "application/x-sv4crc", ".sv4crc");
  add_mime_type("Systems Biology Markup Language", "application/sbml+xml", ".sbml");
  add_mime_type("Tab Seperated Values", "text/tab-separated-values", ".tsv");
  add_mime_type("Tagged Image File Format", "image/tiff", ".tiff");
  add_mime_type("Tao Intent", "application/vnd.tao.intent-module-archive", ".tao");
  add_mime_type("Tar File (Tape Archive)", "application/x-tar", ".tar");
  add_mime_type("Tcl Script", "application/x-tcl", ".tcl");
  add_mime_type("TeX", "application/x-tex", ".tex");
  add_mime_type("TeX Font Metric", "application/x-tex-tfm", ".tfm");
  add_mime_type("Text Encoding and Interchange", "application/tei+xml", ".tei");
  add_mime_type("Text File", "text/plain", ".txt");
  add_mime_type("TIBCO Spotfire", "application/vnd.spotfire.dxp", ".dxp");
  add_mime_type("TIBCO Spotfire", "application/vnd.spotfire.sfs", ".sfs");
  add_mime_type("Time Stamped Data Envelope", "application/timestamped-data", ".tsd");
  add_mime_type("TRI Systems Config", "application/vnd.trid.tpt", ".tpt");
  add_mime_type("Triscape Map Explorer", "application/vnd.triscape.mxs", ".mxs");
  add_mime_type("troff", "text/troff", ".t");
  add_mime_type("True BASIC", "application/vnd.trueapp", ".tra");
  add_mime_type("TrueType Font", "application/x-font-ttf", ".ttf");
  add_mime_type("Turtle (Terse RDF Triple Language)", "text/turtle", ".ttl");
  add_mime_type("UMAJIN", "application/vnd.umajin", ".umj");
  add_mime_type("Unique Object Markup Language", "application/vnd.uoml+xml", ".uoml");
  add_mime_type("Unity 3d", "application/vnd.unity", ".unityweb");
  add_mime_type("Universal Forms Description Language", "application/vnd.ufdl", ".ufd");
  add_mime_type("URI Resolution Services", "text/uri-list", ".uri");
  add_mime_type("User Interface Quartz - Theme (Symbian)", "application/vnd.uiq.theme", ".utz");
  add_mime_type("Ustar (Uniform Standard Tape Archive)", "application/x-ustar", ".ustar");
  add_mime_type("UUEncode", "text/x-uuencode", ".uu");
  add_mime_type("vCalendar", "text/x-vcalendar", ".vcs");
  add_mime_type("vCard", "text/x-vcard", ".vcf");
  add_mime_type("Video CD", "application/x-cdlink", ".vcd");
  add_mime_type("Viewport+", "application/vnd.vsf", ".vsf");
  add_mime_type("Virtual Reality Modeling Language", "model/vrml", ".wrl");
  add_mime_type("VirtualCatalog", "application/vnd.vcx", ".vcx");
  add_mime_type("Virtue MTS", "model/vnd.mts", ".mts");
  add_mime_type("Virtue VTU", "model/vnd.vtu", ".vtu");
  add_mime_type("Visionary", "application/vnd.visionary", ".vis");
  add_mime_type("Vivo", "video/vnd.vivo", ".viv");
  add_mime_type("Voice Browser Call Control", "application/ccxml+xml,", ".ccxml");
  add_mime_type("VoiceXML", "application/voicexml+xml", ".vxml");
  add_mime_type("WAIS Source", "application/x-wais-source", ".src");
  add_mime_type("WAP Binary XML (WBXML)", "application/vnd.wap.wbxml", ".wbxml");
  add_mime_type("WAP Bitamp (WBMP)", "image/vnd.wap.wbmp", ".wbmp");
  add_mime_type("Waveform Audio File Format (WAV)", "audio/x-wav", ".wav");
  add_mime_type("Web Distributed Authoring and Versioning", "application/davmount+xml", ".davmount");
  add_mime_type("Web Open Font Format", "application/x-font-woff", ".woff");
  add_mime_type("Web Services Policy", "application/wspolicy+xml", ".wspolicy");
  add_mime_type("WebP Image", "image/webp", ".webp");
  add_mime_type("WebTurbo", "application/vnd.webturbo", ".wtb");
  add_mime_type("Widget Packaging and XML Configuration", "application/widget", ".wgt");
  add_mime_type("WinHelp", "application/winhlp", ".hlp");
  add_mime_type("Wireless Markup Language (WML)", "text/vnd.wap.wml", ".wml");
  add_mime_type("Wireless Markup Language Script (WMLScript)", "text/vnd.wap.wmlscript", ".wmls");
  add_mime_type("WMLScript", "application/vnd.wap.wmlscriptc", ".wmlsc");
  add_mime_type("Wordperfect", "application/vnd.wordperfect", ".wpd");
  add_mime_type("Worldtalk", "application/vnd.wt.stf", ".stf");
  add_mime_type("WSDL - Web Services Description Language", "application/wsdl+xml", ".wsdl");
  add_mime_type("X BitMap", "image/x-xbitmap", ".xbm");
  add_mime_type("X PixMap", "image/x-xpixmap", ".xpm");
  add_mime_type("X Window Dump", "image/x-xwindowdump", ".xwd");
  add_mime_type("X.509 Certificate", "application/x-x509-ca-cert", ".der");
  add_mime_type("Xfig", "application/x-xfig", ".fig");
  add_mime_type("XHTML - The Extensible HyperText Markup Language", "application/xhtml+xml", ".xhtml");
  add_mime_type("XML - Extensible Markup Language", "application/xml", ".xml");
  add_mime_type("XML Configuration Access Protocol - XCAP Diff", "application/xcap-diff+xml", ".xdf");
  add_mime_type("XML Encryption Syntax and Processing", "application/xenc+xml", ".xenc");
  add_mime_type("XML Patch Framework", "application/patch-ops-error+xml", ".xer");
  add_mime_type("XML Resource Lists", "application/resource-lists+xml", ".rl");
  add_mime_type("XML Resource Lists", "application/rls-services+xml", ".rs");
  add_mime_type("XML Resource Lists Diff", "application/resource-lists-diff+xml", ".rld");
  add_mime_type("XML Transformations", "application/xslt+xml", ".xslt");
  add_mime_type("XML-Binary Optimized Packaging", "application/xop+xml", ".xop");
  add_mime_type("XPInstall - Mozilla", "application/x-xpinstall", ".xpi");
  add_mime_type("XSPF - XML Shareable Playlist Format", "application/xspf+xml", ".xspf");
  add_mime_type("XUL - XML User Interface Language", "application/vnd.mozilla.xul+xml", ".xul");
  add_mime_type("XYZ File Format", "chemical/x-xyz", ".xyz");
  add_mime_type("YAML Ain't Markup Language / Yet Another Markup Language", "text/yaml", ".yaml");
  add_mime_type("YANG Data Modeling Language", "application/yang", ".yang");
  add_mime_type("YIN (YANG - XML)", "application/yin+xml", ".yin");
  add_mime_type("Z.U.L. Geometry", "application/vnd.zul", ".zir");
  add_mime_type("Zip Archive", "application/zip", ".zip");
  add_mime_type("ZVUE Media Manager", "application/vnd.handheld-entertainment+xml", ".zmm");
  add_mime_type("Zzazz Deck", "application/vnd.zzazz.deck+xml", ".zaz");
}
